modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="minebbb"
version="1.0.0"
displayName="Mine BBB"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://slatt.team/"
authors="HYPER, MCreator"
description="A open source backrooms mod."

[[dependencies.minebbb]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




